### ISSUE TITLE
what is package_web_dir ? 

### ISSUE THREAD

**Issue by LiNk-NY** [r-devel/repos#1]
Hi Kurt, @kurthornik
Thanks for the starter code. 

What does the `package_web_dir` object look like and how do we generate it? 

e.g., 

https://github.com/r-devel/repos/blob/9ed91e1cc08f2c116d1288be350c0c7c47ac992b/R/aliases.R#L11

Thanks!

**Comment by llrs** [comment]
The file is available at http://cran.r-project.org/src/contrib/Meta/aliases.rds.
I think `package_web_dir` is simply the folder that serves the website.

**Comment by LiNk-NY** [comment]
Ok, so it seems like the `package_web_dir` is
`https://cran.r-project.org/web/packages/<PACKAGE>` because it has
https://cran.r-project.org/web/packages/BiocManager/aliases.rds
