### ISSUE TITLE
rename branch from master to devel

### ISSUE THREAD

**Issue by LiNk-NY** [r-devel/repos#2]
@llrs or anyone with admin rights

**Comment by llrs** [comment]
While the change might be trivial, anyone who has cloned the repo will need to change their local configuration.
Could you explain the reasons behind asking for this change now?

**Comment by LiNk-NY** [comment]
Anyone who has cloned the repo can do : 

```
git checkout master
git branch -m devel
```

Bioconductor has moved away from the term "master". For more info, see our post here: 

https://blog.bioconductor.org/posts/2023-03-01-transition-to-devel/

**Comment by lshep** [comment]
as has github as well since the default for new repos is also now main for them too

**Comment by llrs** [comment]
Not all existing collaborators might be used to these steps or git. 
I will change this, hoping that we all can make this update. 

Keep in mind, @lshep and @LiNk-NY, this project/repo and organization is not specific for Bioconductor and aims for more general use.

**Comment by lshep** [comment]
we understand but we also have a bioconductor code of conduct to follow.  If its aimed at general use than using the github default of main seems more appropriate for those less familiar.  we appreciate the change.

**Comment by llrs** [comment]
I know the Bioconductor code of conduct: I am currently part of the Bioconductor's Code of Conduct committee.
This was was not the reason given! But let's move on.
